service: client
app: thoughtful-automation
org: jordmax12
frameworkVersion: '^3'
configValidationMode: error

provider:
  name: aws
  region: us-east-2

plugins:
  - serverless-s3-sync
  - serverless-plugin-scripts

custom:
  bucketName: ${self:service}-${sls:stage}-bucket
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: app/build
  scripts:
    hooks:
      before:deploy:deploy: (cd ./app && yarn run build)

resources:
    Resources:
      ReactAppBucket:
        Type: AWS::S3::Bucket
        Properties:
          BucketName: ${self:custom.bucketName}
          AccessControl: PublicRead
          WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: index.html
      S3AccessPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket:
            Ref: ReactAppBucket
          PolicyDocument:
            Statement:
              - Sid: PublicReadGetObject
                Effect: Allow
                Principal: '*'
                Action:
                    - s3:GetObject
                Resource: arn:aws:s3:::${self:custom.bucketName}/*
      CloudFrontDistribution:
        Type: AWS::CloudFront::Distribution
        Properties:
          DistributionConfig:
            Origins:
              - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                Id: ReactApp
                CustomOriginConfig:
                  HTTPPort: 80
                  HTTPSPort: 443
                  OriginProtocolPolicy: https-only
            Aliases:
              - thoughtful.jordanmax.io
              - www.thoughtful.jordanmax.io
            # ViewerCertificate:
            #   AcmCertificateArn: ${param:certificateArn}
            #   MinimumProtocolVersion: TLSv1.2_2019
            #   SslSupportMethod: sni-only
            Enabled: 'true'
            DefaultRootObject: index.html
            CustomErrorResponses:
              - ErrorCode: 404
                ResponseCode: 200
                ResponsePagePath: /index.html
            DefaultCacheBehavior:
              AllowedMethods:
                  - DELETE
                  - GET
                  - HEAD
                  - OPTIONS
                  - PATCH
                  - POST
                  - PUT
              TargetOriginId: ReactApp
              ForwardedValues:
                  QueryString: 'false'
                  Cookies:
                      Forward: none
              ViewerProtocolPolicy: redirect-to-https
