service: api
app: thoughtful-automation
org: jordmax12
frameworkVersion: '3'

provider:
  name: aws
  region: us-east-2
  runtime: nodejs16.x
  architecture: arm64
  environment:
    STAGE: ${sls:stage}
    OTP_TABLE: ${cf:database-${sls:stage}.OTP}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:DeleteItem
            - dynamodb:Scan
          Resource:
            - '${cf:database-${sls:stage}.OTPArn}'
            - '${cf:database-${sls:stage}.OTPArn}/*'

functions:
  requestOneTimePassword:
    handler: request-otp.handler
    events:
      - httpApi:
          path: /
          method: get
  resendOneTimePassword:
    handler: request-otp.handler
    events:
      - httpApi:
          path: /resend
          method: get
  verifyOneTimePassword:
    handler: verify-otp.handler
    events:
      - httpApi:
          path: /verify
          method: get
  otpListener:
    handler: otp-listener.handler
    timeout: 900
    events:
      - stream:
          type: dynamodb
          arn: ${cf:database-${sls:stage}.OTPStreamArn}
          startingPosition: LATEST
          batchSize: 450
          enabled: true
