const LOGIN_FLOWS = {
    'LOGIN': 'LOGIN',
    'REQUEST_OTP': 'REQUEST_OTP',
    'VERIFY_OTP': 'VERIFY_OTP',
    'VERIFIED_OTP': 'VERIFIED_OTP',
    'LOGGED_IN': 'LOGGED_IN',
    'LOGGING_IN': 'LOGGING_IN',
}

export default LOGIN_FLOWS;